[package]
name = "vulkan"
description = "Vulkan raw bindings"
version = "0.10.0"
authors = ["Lance Hart <me@lancehart.ca>"]
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/shipsimfan/lib-vulkan"
publish = false

[features]
link = []

win32 = ["dep:win32"]
wayland = ["dep:wayland"]


[target.'cfg(windows)'.dependencies]
win32 = { git = "https://github.com/shipsimfan/lib-win32", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
wayland = { git = "https://github.com/shipsimfan/lib-wayland", optional = true }
