[workspace]
default-members = ["vulkan"]

members = ["vulkan", "loader", "loaders/native"]

[workspace.package]
authors = ["Lance Hart <me@lancehart.ca>"]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/shipsimfan/lib-vulkan"

[workspace.dependencies]
loader = { path = "loader" }

native = { path = "loaders/native" }
