[package]
name = "vulkan"
version = "0.1.0"
description = "Vulkan wrapper library"

authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[workspace]

[workspace.package]
authors = ["Lance Hart <me@lancehart.ca>"]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/shipsimfan/lib-vulkan"
