use crate::flags;

// rustdoc imports
#[allow(unused_imports)]
use crate::{VK_VERSION_1_0, VkPipelineStageFlag};

flags! {
    /// Bitmask of [`VkPipelineColorBlendStateCreateFlag`]s
    ///
    /// # Description
    /// [`VkPipelineColorBlendStateCreateFlags`] is a bitmask type for setting a mask of zero or
    /// more [`VkPipelineColorBlendStateCreateFlag`].
    ///
    /// Provided by [`VK_VERSION_1_0`]
    pub struct VkPipelineColorBlendStateCreateFlags;

    /// Bitmask specifying additional parameters of an image
    ///
    /// # Description
    /// When [`VkPipelineColorBlendStateCreateFlag::RasterizationOrderAttachmnetAccessExt`] is
    /// included in a pipeline, it forms a framebuffer-local memory dependency for each fragment
    /// generated by draw commands for that pipeline with the following scopes:
    ///  - The first synchronization scope includes the
    ///    [`VkPipelineStageFlag::ColorAttachmentOutput`] pipeline stage executed by all previous
    ///    fragments (as defined by primitive order) in the corresponding framebuffer regions
    ///    including those generated by the same draw command.
    ///  - The second synchronization scope includes the [`VkPipelineStageFlag::FragmentShader`]
    ///    pipeline stage executed by the generated fragment.
    ///  - The first access scope includes all writes to color attachments.
    ///  - The second access scope includes all reads from input attachments.
    ///
    /// Provided by [`VK_VERSION_1_0`]
    pub enum VkPipelineColorBlendStateCreateFlag {
        /// [`VkPipelineColorBlendStateCreateFlag::RasterizationOrderAttachmnetAccessExt`]
        /// specifies that access to color and input attachments will have implicit
        /// framebuffer-local memory dependencies, allowing applications to express custom blending
        /// operations in a fragment shader.
        ///
        /// Provided by [`ext_rasterization_order_attachment_access`]
        RasterizationOrderAttachmnetAccessExt = 0x00000001,
    }
}
