use crate::macros::flags;

// rustdoc imports
#[allow(unused_imports)]
use crate::VK_VERSION_1_0;

flags! {
    /// Bitmask of [`VkQueryPipelineStatisticFlag`]
    ///
    /// # Description
    /// [`VkQueryPipelineStatisticFlags`] is a bitmask type for setting a mask of zero or more
    /// [`VkQueryPipelineStatisticFlag`]s.
    ///
    /// Provided by [`VK_VERSION_1_0`]
    pub struct VkQueryPipelineStatisticFlags;


    /// Bitmask specifying queried pipeline statistics
    ///
    /// # Description
    /// These values are intended to measure relative statistics on one implementation. Various
    /// device architectures will count these values differently. Any or all counters may be
    /// affected by the issues described in query operation.
    ///
    /// This counting difference is especially true if the pipeline contains mesh or task shaders,
    /// which may affect several of the counters in unexpected ways.
    ///
    /// If a pipeline has `rasterizer_discard_enable` enabled, implementations may discard
    /// primitives after the final pre-rasterization shader stage. As a result, if
    /// `rasterizer_discard_enable` is enabled, the clipping input and output primitives counters
    /// may not be incremented.
    ///
    /// When a pipeline statistics query finishes, the result for that query is marked as
    /// available. The application can copy the result to a buffer (via
    /// [`VkCmdCopyQueryPoolResults`]), or request it be put into host memory (via
    /// [`VkGetQueryPoolResults`]).
    ///
    /// Provided by [`VK_VERSION_1_0`]
    pub enum VkQueryPipelineStatisticFlag {
        /// [`VkQueryPipelineStatisticFlag::InputAsssemblyVerticesBit`] specifies that queries
        /// managed by the pool will count the number of vertices processed by the input assembly
        /// stage. Vertices corresponding to incomplete primitives may contribute to the count.
        InputAsssemblyVerticesBit = 0x00000001,

        /// [`VkQueryPipelineStatisticFlag::InputAssemblyPrimitivesBit`] specifies that queries
        /// managed by the pool will count the number of primitives processed by the input assembly
        /// stage. If primitive restart is enabled, restarting the primitive topology has no effect
        /// on the count. Incomplete primitives may be counted.
        InputAssemblyPrimitivesBit = 0x00000002,

        /// [`VkQueryPipelineStatisticFlag::VertexShaderInvocationsBit`] specifies that queries
        /// managed by the pool will count the number of vertex shader invocations. This counter’s
        /// value is incremented each time a vertex shader is invoked.
        VertexShaderInvocationsBit = 0x00000004,

        /// [`VkQueryPipelineStatisticFlag::GeometryShaderInvocationsBit`] specifies that queries
        /// managed by the pool will count the number of geometry shader invocations. This
        /// counter’s value is incremented each time a geometry shader is invoked. In the case of
        /// instanced geometry shaders, the geometry shader invocations count is incremented for
        /// each separate instanced invocation.
        GeometryShaderInvocationsBit = 0x00000008,

        /// [`VkQueryPipelineStatisticFlag::GeometryShaderPrimitivesBit`] specifies that queries
        /// managed by the pool will count the number of primitives generated by geometry shader
        /// invocations. The counter’s value is incremented each time the geometry shader emits a
        /// primitive. Restarting primitive topology using the SPIR-V instructions `OpEndPrimitive`
        /// or `OpEndStreamPrimitive` has no effect on the geometry shader output primitives count.
        GeometryShaderPrimitivesBit = 0x00000010,

        /// [`VkQueryPipelineStatisticFlag::ClippingInvocationsBit`] specifies that queries managed
        /// by the pool will count the number of primitives processed by the Primitive Clipping
        /// stage of the pipeline. The counter’s value is incremented each time a primitive reaches
        /// the primitive clipping stage.
        ClippingInvocationsBit = 0x00000020,

        /// [`VkQueryPipelineStatisticFlag::ClippingPrimitivesBit`] specifies that queries managed
        /// by the pool will count the number of primitives output by the Primitive Clipping stage
        /// of the pipeline. The counter’s value is incremented each time a primitive passes the
        /// primitive clipping stage. The actual number of primitives output by the primitive
        /// clipping stage for a particular input primitive is implementation-dependent but must
        /// satisfy the following conditions:
        ///  - If at least one vertex of the input primitive lies inside the clipping volume, the
        ///    counter is incremented by one or more.
        ///  - Otherwise, the counter is incremented by zero or more.
        ClippingPrimitivesBit = 0x00000040,

        /// [`VkQueryPipelineStatisticFlag::FragmentShaderInvocationsBit`] specifies that queries
        /// managed by the pool will count the number of fragment shader invocations. The counter’s
        /// value is incremented each time the fragment shader is invoked.
        FragmentShaderInvocationsBit = 0x00000080,

        /// [`VkQueryPipelineStatisticFlag::TessellationControlShaderPatchesBit`] specifies that
        /// queries managed by the pool will count the number of patches processed by the
        /// tessellation control shader. The counter’s value is incremented once for each patch for
        /// which a tessellation control shader is invoked.
        TessellationControlShaderPatchesBit = 0x00000100,

        /// [`VkQueryPipelineStatisticFlag::TessellationEvaluationShaderInvocationsBit`] specifies
        /// that queries managed by the pool will count the number of invocations of the
        /// tessellation evaluation shader. The counter’s value is incremented each time the
        /// tessellation evaluation shader is invoked.
        TessellationEvaluationShaderInvocationsBit = 0x00000200,

        /// [`VkQueryPipelineStatisticFlag::ComputeShaderInvocationsBit`] specifies that queries
        /// managed by the pool will count the number of compute shader invocations. The counter’s
        /// value is incremented every time the compute shader is invoked. Implementations may skip
        /// the execution of certain compute shader invocations or execute additional compute
        /// shader invocations for implementation-dependent reasons as long as the results of
        /// rendering otherwise remain unchanged.
        ComputeShaderInvocationsBit = 0x00000400,

        /// [`VkQueryPipelineStatisticFlag::TaskShaderInvocationsBitExt`] specifies that queries
        /// managed by the pool will count the number of task shader invocations. The counter’s
        /// value is incremented every time the task shader is invoked.
        ///
        /// Provided by [`ext_mesh_shader`]
        TaskShaderInvocationsBitExt = 0x00000800,

        /// [`VkQueryPipelineStatisticFlag::MeshShaderInvocationsBitExt`] specifies that queries
        /// managed by the pool will count the number of mesh shader invocations. The counter’s
        /// value is incremented every time the mesh shader is invoked.
        ///
        /// Provided by [`ext_mesh_shader`]
        MeshShaderInvocationsBitExt = 0x00001000,

        /// Provided by [`huawei_cluster_culling_shader`]
        ClusterCullingShaderInvocationsBitHuawei = 0x00002000,
    }
}
