use crate::flags;

// rustdoc imports
#[allow(unused_imports)]
use crate::{VK_VERSION_1_0, VkPipelineStageFlag};

flags! {
    /// Bitmask of [`VkPipelineDepthStencilStateCreateFlag`]
    ///
    /// # Description
    /// [`VkPipelineDepthStencilStateCreateFlags`] is a bitmask type for setting a mask of zero or
    /// more [`VkPipelineDepthStencilStateCreateFlag`].
    ///
    /// Provided by [`VK_VERSION_1_0`]
    pub struct VkPipelineDepthStencilStateCreateFlags;

    /// When
    /// [`VkPipelineDepthStencilStateCreateFlag::RasterizationOrderAttachmentStencilAcccessExt`] is
    /// included in a pipeline, it forms a framebuffer-local memory dependency for each fragment
    /// generated by draw commands for that pipeline with the following scopes:
    ///  - The first synchronization scope includes [`VkPipelineStageFlag::FragmentShader`] and
    ///    [`VkPipelineStageFlag::LateFragmentTests`] pipeline stages executed by all previous
    ///    fragments (as defined by primitive order) in the corresponding framebuffer regions
    ///    including those generated by the same draw command.
    ///  - The second synchronization scope includes [`VkPipelineStageFlag::FragmentShader`] and
    ///    [`VkPipelineStageFlag::LateFragmentTests`] pipeline stages executed by the generated
    ///    fragment.
    ///  - The first access scope includes all writes to the stencil aspect of depth/stencil
    ///    attachments.
    ///  - The second access scope includes all reads from the stencil aspect of input attachments.
    ///
    /// Provided by [`VK_VERSION_1_0`]
    pub enum VkPipelineDepthStencilStateCreateFlag {
        /// [`VkPipelineDepthStencilStateCreateFlag::RasterizationOrderAttachmentDepthAcccessExt`]
        /// specifies that access to the depth aspects of depth/stencil and input attachments will
        /// have implicit framebuffer-local memory dependencies.
        ///
        /// Provided by [`ext_rasterization_order_attachment_access`]
        RasterizationOrderAttachmentDepthAcccessExt = 0x00000001,

        /// [`VkPipelineDepthStencilStateCreateFlag::RasterizationOrderAttachmentStencilAcccessExt`]
        /// specifies that access to the stencil aspects of depth/stencil and input attachments
        /// will have implicit framebuffer-local memory dependencies.
        ///
        /// Provided by [`ext_rasterization_order_attachment_access`]
        RasterizationOrderAttachmentStencilAcccessExt = 0x00000002,
    }
}
